apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: azurevotefront 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azurevotefront 
    spec:
      containers:
        - name: azurevotefront 
          image: akirainaks.azurecr.io/azurevotefront
          ports:
          - containerPort: 80